# Generated by Django 2.0.1 on 2020-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_view', '0004_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
