# Generated by Django 2.0.1 on 2020-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_view', '0005_auto_20200106_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
