# Generated by Django 2.0.1 on 2020-01-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_view', '0006_auto_20200106_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'high'), ('2', 'medium'), ('3', 'low')], max_length=50),
        ),
    ]
