# Generated by Django 2.0.1 on 2020-01-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_view', '0007_auto_20200107_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(default='profile_pics/index.png', upload_to='profile_pics'),
        ),
    ]
